/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt 
    to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to 
    edit this template
 */

package com.zero.hunger.care4dublinapp;

/*
Aidas Kibas
08.03.26
NewRecordPage.java
*/

public class NewRecordPage extends javax.swing.JFrame { /* JFrame is a java 
    class type that allows for a simple GUI.*/
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewRecordPage.class.getName());
    private static int nextId = 1; // Declaring a static variable called nextID
    
    /**
     * Creates new form NewRecordPage
     */
    
    public NewRecordPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn2 = new javax.swing.JButton();
        clearBtn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nrpDisplay = new javax.swing.JTextArea();
        nrpDisplayLabel = new javax.swing.JLabel();
        newRecordPageLabel = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        issueLabel = new javax.swing.JLabel();
        severityLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        issueField = new javax.swing.JTextField();
        severityField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        priorityDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        closeBtn2.setBackground(new java.awt.Color(204, 204, 204));
        closeBtn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        closeBtn2.setText("Close App");
        closeBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtn2ActionPerformed(evt);
            }
        });

        clearBtn2.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearBtn2.setText("Clear Display");
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });

        nrpDisplay.setEditable(false);
        nrpDisplay.setBackground(new java.awt.Color(204, 204, 204));
        nrpDisplay.setColumns(20);
        nrpDisplay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nrpDisplay.setRows(5);
        jScrollPane1.setViewportView(nrpDisplay);

        nrpDisplayLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nrpDisplayLabel.setText("Display Area");

        newRecordPageLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        newRecordPageLabel.setText("Care4Dublin - New Record Page");

        submitBtn.setBackground(new java.awt.Color(204, 204, 204));
        submitBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitBtn.setText("SUBMIT RECORD");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameLabel.setText("NAME:");

        issueLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        issueLabel.setText("ISSUE:");

        severityLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        severityLabel.setText("SEVERITY:");

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        priorityDisplay.setEditable(false);
        priorityDisplay.setColumns(20);
        priorityDisplay.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        priorityDisplay.setRows(5);
        priorityDisplay.setText("1 - Lowest Priority\n2 - Low Priority\n3 - Medium Priority\n4 - High Priority\n5 - Urgent Priority");
        jScrollPane2.setViewportView(priorityDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(closeBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(newRecordPageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nrpDisplayLabel)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clearBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(issueLabel)
                                            .addComponent(nameLabel))
                                        .addGap(45, 45, 45))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(severityLabel)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(issueField)
                                    .addComponent(severityField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(nrpDisplayLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newRecordPageLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueLabel)
                            .addComponent(issueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(severityLabel)
                            .addComponent(severityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clearBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn2ActionPerformed
        System.exit(0); // This code closes the application
    }//GEN-LAST:event_closeBtn2ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String name = nameField.getText().trim(); // Takes each input as a String variable
        String issue = issueField.getText().trim();
        String severityText = severityField.getText().trim();
        
        if(name.isEmpty() || issue.isEmpty() || severityText.isEmpty()){ // Ensures all fields have been filled in
            nrpDisplay.append("---------ERROR---------\nPlease fill all the fields of the form...\n"); // Displays this message if not
        }
        
        /* The .matches() method ensures that the input for name and issue is 
        a String as it would not make any sense for a name to be 123 or Bob1. 
        The same for issue, there cannot be an issue called issue1 - not clear.
        The code says if the name or issue does NOT match a-z, A-Z, or " space "
        then display the error.*/
        
        if(!name.matches("[a-zA-Z ]+")){ 
            nrpDisplay.append("---------ERROR---------\nName MUST contain letters only.\n");
            return;
        }
        
        if(!issue.matches("[a-zA-Z ]+")){
            nrpDisplay.append("---------ERROR---------\nIssue MUST contain letters only.\n");
            return;
        }
        
        else{
            
            /* Declaring severity as an int and parsing the string version from
            the severityText to ensure it functions as an int in the code. */
            
            int severity;
            
            /*Here a try catch method checks if the severity that was parsed
            is in NumberFormat (int). It would not make sense for the severity
            to be "very serious" as then the PQ would not work. It was simpler
            to ensure the input was a number.*/
            
            try{
                severity = Integer.parseInt(severityText);
            } catch(NumberFormatException e){
                nrpDisplay.append("---------ERROR---------\nSeverity MUST be a number between 1-5.\n");
                return;
           
            }
            
            /* Checking if the severity is between 1-5 before displaying 
            the users input as a record added. I had this issue even when i 
            entered a severity int beyond 1-5.*/
            
            if(severity < 1 || severity > 5){
                nrpDisplay.append("---------ERROR---------\nSeverity MUST be between 1-5.\n");
                return;
            } 
            
            /* Declaring a variable called id. Every new record will add 1 to
            the id to ensure the id is unique - this is useful for updating
            records and ensuring all records are unique. */
            
            int id = nextId++; 
            String status = "Pending"; // Stores unresolved issues as pending
            
            /* Then adding the inputs into all of the adts except stack, whilst 
            ensuring that the LandingPage communicates with the NewRecordPage
            for the same data.
            */
  
            Issue newIssue = new Issue(name, issue, severity, id, status);
                
            LandingPage.slli.insert(newIssue);
            LandingPage.qi.enqueue(newIssue);
            LandingPage.pqi.insert(newIssue);
            
            // Message displayed once all fields make sense
            
            nrpDisplay.append("---------Record-Added---------\n"
                    + "Name: "+name+"\n"
                    + "Issue: "+issue+"\n"
                    + "Severity: "+severity+"\n"
                    + "------------------------------\n");
            
            /* This code simply reverts the inputs back to being empty after
            the input has been submitted. */
            
            nameField.setText("");
            issueField.setText("");
            severityField.setText("");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LandingPage lp = new LandingPage();
        lp.setVisible(true); // Allows for landing page to be visible
        dispose(); // Disposes/closes the New Record Page
    }//GEN-LAST:event_backBtnActionPerformed

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        nrpDisplay.setText(""); /* All this code does is set the text in the 
        display area to nothing - essentially clearing the display area.*/
    }//GEN-LAST:event_clearBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewRecordPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JButton closeBtn2;
    private javax.swing.JTextField issueField;
    private javax.swing.JLabel issueLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel newRecordPageLabel;
    private javax.swing.JTextArea nrpDisplay;
    private javax.swing.JLabel nrpDisplayLabel;
    private javax.swing.JTextArea priorityDisplay;
    private javax.swing.JTextField severityField;
    private javax.swing.JLabel severityLabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
